import { ArrowDownToLine, ArrowUpFromLine, ChevronRight, CircleAlert, MoveRight, Package, RefreshCw, WalletCards } from "lucide-react";
import { Link } from "wouter";
import { useGetDashboardSummary, useGetLowStockProducts, useGetRecentMovements } from "@workspace/api-client-react";
import { EmptyState, ErrorState, LoadingState, PageHeader, StatCard, StatusPill } from "@/components/ui";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(value)).replace(".", "");

export default function Dashboard() {
  const summary = useGetDashboardSummary();
  const low = useGetLowStockProducts();
  const recent = useGetRecentMovements({ limit: 6 });
  const retry = () => { summary.refetch(); low.refetch(); recent.refetch(); };
  const loading = summary.isLoading || low.isLoading || recent.isLoading;
  const error = summary.isError || low.isError || recent.isError;
  if (loading) return <><PageHeader eyebrow="SCPE – Gestão Inteligente de Estoque" title="Bom dia, Loja Oliveira." description="Sistema de Controle de Produtos e Estoque · uma leitura rápida do que pede atenção hoje." /><LoadingState rows={6} /></>;
  if (error || !summary.data) return <ErrorState onRetry={retry} />;
  return <div className="animate-rise-in">
    <PageHeader eyebrow="SCPE – Gestão Inteligente de Estoque" title="Bom dia, Loja Oliveira." description="Sistema de Controle de Produtos e Estoque · uma leitura rápida do que pede atenção hoje." action={<div className="flex gap-2"><Link href="/entrada" data-testid="link-dashboard-entry" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground shadow-sm transition hover:-translate-y-0.5"><ArrowDownToLine size={17} />Registrar entrada</Link><Link href="/saida" data-testid="link-dashboard-exit" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-bold text-foreground transition hover:-translate-y-0.5"><ArrowUpFromLine size={17} />Registrar saída</Link></div>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Produtos ativos" value={summary.data.activeProducts} detail="itens cadastrados para venda" icon={<Package size={18} />} />
      <StatCard label="Itens em estoque" value={summary.data.totalItems.toLocaleString("pt-BR")} detail="unidades disponíveis" accent="accent" icon={<BoxesIcon />} />
      <StatCard label="Abaixo do mínimo" value={summary.data.lowStockProducts} detail={summary.data.lowStockProducts ? "pedem reposição" : "nenhum alerta agora"} accent="destructive" icon={<CircleAlert size={18} />} />
      <StatCard label="Valor do estoque" value={money.format(summary.data.stockValue)} detail={`${summary.data.movementsThisMonth} movimentos este mês`} icon={<WalletCards size={18} />} />
    </div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-xl border border-card-border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-extrabold tracking-[-.03em]">Atenção necessária</h2><p className="mt-1 text-sm text-muted-foreground">Produtos no limite ou abaixo dele.</p></div><Link href="/produtos" className="flex items-center gap-1 text-xs font-extrabold text-primary" data-testid="link-low-stock">Ver todos <ChevronRight size={15} /></Link></div>
        {!low.data?.length ? <EmptyState title="Estoque saudável" detail="Nenhum produto abaixo do mínimo definido." /> : <div className="divide-y divide-border">{low.data.slice(0, 5).map((product) => <div key={product.id} data-testid={`row-low-stock-${product.id}`} className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div className="min-w-0"><div className="truncate text-sm font-bold">{product.name}</div><div className="mt-1 font-mono text-[11px] text-muted-foreground">{product.code}</div></div><div className="flex shrink-0 items-center gap-4"><div className="text-right"><div className="font-mono text-sm font-bold">{product.currentStock} <span className="font-sans text-xs font-medium text-muted-foreground">un.</span></div><div className="text-[11px] text-muted-foreground">mín. {product.minimumStock}</div></div><StatusPill status={product.currentStock === 0 ? "OUT" : "LOW"} /></div></div>)}</div>}
      </section>
      <section className="rounded-xl border border-card-border bg-card p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-lg font-extrabold tracking-[-.03em]">Últimas movimentações</h2><p className="mt-1 text-sm text-muted-foreground">O pulso do seu estoque.</p></div><Link href="/movimentacoes" className="flex items-center gap-1 text-xs font-extrabold text-primary" data-testid="link-recent-movements">Histórico <ChevronRight size={15} /></Link></div>
        {!recent.data?.length ? <EmptyState title="Nenhum movimento ainda" detail="As entradas e saídas aparecerão aqui." /> : <div className="grid gap-3">{recent.data.map((movement) => <div key={movement.id} data-testid={`row-recent-movement-${movement.id}`} className="flex items-center gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${movement.type === "ENTRY" ? "bg-primary/10 text-primary" : "bg-accent/20 text-foreground"}`}>{movement.type === "ENTRY" ? <ArrowDownToLine size={16} /> : <ArrowUpFromLine size={16} />}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{movement.productName}</div><div className="mt-0.5 text-xs text-muted-foreground">{movement.type === "ENTRY" ? "Entrada" : "Saída"} · {date(movement.movementDate)}</div></div><span className={`font-mono text-sm font-bold ${movement.type === "ENTRY" ? "text-primary" : "text-foreground"}`}>{movement.type === "ENTRY" ? "+" : "−"}{movement.quantity}</span></div>)}</div>}
      </section>
    </div>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Link href="/produtos/novo" data-testid="link-quick-new-product" className="group rounded-xl border border-card-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/50"><span className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-foreground"><Package size={18} /></span><div className="mt-4 text-sm font-extrabold">Cadastrar produto</div><div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground group-hover:text-primary">Comece um novo cadastro <MoveRight size={14} /></div></Link><Link href="/relatorios" data-testid="link-quick-reports" className="group rounded-xl border border-card-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/50"><span className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-foreground"><RefreshCw size={18} /></span><div className="mt-4 text-sm font-extrabold">Conferir relatórios</div><div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground group-hover:text-primary">Veja a saúde do estoque <MoveRight size={14} /></div></Link><Link href="/movimentacoes" data-testid="link-quick-history" className="group rounded-xl border border-card-border bg-card p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/50"><span className="grid h-9 w-9 place-items-center rounded-lg bg-secondary text-foreground"><ClipboardIcon /></span><div className="mt-4 text-sm font-extrabold">Auditar movimentações</div><div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground group-hover:text-primary">Encontre qualquer registro <MoveRight size={14} /></div></Link></section>
  </div>;
}
function BoxesIcon() { return <Package size={18} />; }
function ClipboardIcon() { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="5" y="4" width="14" height="17" rx="2" /><path d="M9 4V2h6v2M9 11h6M9 15h4" /></svg>; }