import { ArrowDownToLine, ArrowUpFromLine, CalendarRange, FilterX, Search } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useListMovements, useListProducts } from "@workspace/api-client-react";
import { Button, EmptyState, ErrorState, Input, LoadingState, PageHeader, Select, SelectChevron } from "@/components/ui";

const fmt = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(value));
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export default function Movements() {
  const [productId, setProductId] = useState(""); const [type, setType] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [applied, setApplied] = useState({ productId: "", type: "", from: "", to: "" });
  const query = useListMovements({ productId: applied.productId ? Number(applied.productId) : undefined, type: (applied.type || undefined) as "ENTRY" | "EXIT" | undefined, from: applied.from || undefined, to: applied.to || undefined, limit: 100 }); const products = useListProducts({ active: true });
  const apply = (e: FormEvent) => { e.preventDefault(); setApplied({ productId, type, from, to }); }; const clear = () => { setProductId(""); setType(""); setFrom(""); setTo(""); setApplied({ productId: "", type: "", from: "", to: "" }); };
  return <div className="animate-rise-in"><PageHeader eyebrow="Auditoria" title="Movimentações" description="Consulte cada entrada e saída registrada no estoque." />
    <form onSubmit={apply} className="mb-6 grid gap-3 rounded-xl border border-card-border bg-card p-4 shadow-sm sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_1fr_auto] lg:items-end"><div className="relative"><label className="mb-1.5 block text-xs font-bold text-muted-foreground">Produto</label><Select value={productId} onChange={(e) => setProductId(e.target.value)} data-testid="select-filter-product"><option value="">Todos os produtos</option>{products.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select><SelectChevron /></div><div className="relative"><label className="mb-1.5 block text-xs font-bold text-muted-foreground">Tipo</label><Select value={type} onChange={(e) => setType(e.target.value)} data-testid="select-filter-type"><option value="">Entradas e saídas</option><option value="ENTRY">Entradas</option><option value="EXIT">Saídas</option></Select><SelectChevron /></div><div><label className="mb-1.5 block text-xs font-bold text-muted-foreground">De</label><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} data-testid="input-filter-from" /></div><div><label className="mb-1.5 block text-xs font-bold text-muted-foreground">Até</label><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} data-testid="input-filter-to" /></div><div className="flex gap-2"><Button type="submit" data-testid="button-apply-filters" className="flex-1 bg-primary text-primary-foreground"><Search size={16} />Filtrar</Button><Button type="button" onClick={clear} data-testid="button-clear-filters" className="border border-border bg-background px-3 text-muted-foreground" aria-label="Limpar filtros"><FilterX size={16} /></Button></div></form>
    <section className="overflow-hidden rounded-xl border border-card-border bg-card shadow-sm">{query.isLoading ? <div className="p-5"><LoadingState rows={7} /></div> : query.isError ? <div className="p-5"><ErrorState onRetry={() => query.refetch()} /></div> : !query.data?.length ? <div className="p-5"><EmptyState title="Nenhuma movimentação encontrada" detail="Ajuste os filtros ou registre uma nova entrada ou saída." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="border-b border-border bg-muted/50 text-[11px] uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-5 py-3.5 font-extrabold">Data</th><th className="px-4 py-3.5 font-extrabold">Produto</th><th className="px-4 py-3.5 font-extrabold">Tipo</th><th className="px-4 py-3.5 font-extrabold">Quantidade</th><th className="px-4 py-3.5 font-extrabold">Saldo após</th><th className="px-5 py-3.5 font-extrabold">Motivo</th></tr></thead><tbody className="divide-y divide-border">{query.data.map((m) => <tr key={m.id} data-testid={`row-movement-${m.id}`} className="transition hover:bg-muted/30"><td className="px-5 py-4 font-mono text-xs text-muted-foreground">{fmt(m.movementDate)}</td><td className="px-4 py-4"><div className="text-sm font-bold">{m.productName}</div><div className="mt-1 text-xs text-muted-foreground">saldo anterior: {m.stockBefore}</div></td><td className="px-4 py-4"><span className={`inline-flex items-center gap-1.5 text-xs font-extrabold ${m.type === "ENTRY" ? "text-primary" : "text-foreground"}`}>{m.type === "ENTRY" ? <ArrowDownToLine size={15} /> : <ArrowUpFromLine size={15} />}{m.type === "ENTRY" ? "Entrada" : "Saída"}</span></td><td className={`px-4 py-4 font-mono text-sm font-bold ${m.type === "ENTRY" ? "text-primary" : "text-foreground"}`}>{m.type === "ENTRY" ? "+" : "−"}{m.quantity}{m.unitPrice != null && <div className="mt-1 text-[11px] font-normal text-muted-foreground">{money.format(m.unitPrice)} / un.</div>}</td><td className="px-4 py-4 font-mono text-sm font-bold">{m.stockAfter} un.</td><td className="max-w-[180px] px-5 py-4 text-sm text-muted-foreground">{m.reason || "—"}</td></tr>)}</tbody></table></div>}</section>
    <div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><CalendarRange size={14} />{query.data?.length || 0} registros encontrados</div>
  </div>;
}