import { CheckCircle2, Edit3, Filter, Plus, Search, ToggleLeft, ToggleRight } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";
import { useListProducts, useToggleProductStatus, getListProductsQueryKey, getGetDashboardSummaryQueryKey, getGetLowStockProductsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Button, EmptyState, ErrorState, Input, LoadingState, PageHeader, Select, StatusPill } from "@/components/ui";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export default function Products() {
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("all");
  const params = { ...(search ? { search } : {}), ...(filter === "active" ? { active: true } : filter === "inactive" ? { active: false } : filter === "low" ? { lowStock: true } : {}) };
  const query = useListProducts(params);
  const qc = useQueryClient(); const toggle = useToggleProductStatus();
  const products = query.data || [];
  const refresh = () => query.refetch();
  return <div className="animate-rise-in"><PageHeader eyebrow="Catálogo" title="Produtos" description="Mantenha seu catálogo claro e o saldo sempre confiável." action={<Link href="/produtos/novo" data-testid="link-new-product" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground shadow-sm transition hover:-translate-y-0.5"><Plus size={17} />Novo produto</Link>} />
    <div className="mb-5 flex flex-col gap-3 md:flex-row"><div className="relative max-w-lg flex-1"><Search className="absolute left-3.5 top-3 text-muted-foreground" size={17} /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nome ou código..." className="pl-10" data-testid="input-search-products" /></div><div className="relative w-full md:w-48"><Filter className="pointer-events-none absolute left-3 top-3.5 text-muted-foreground" size={15} /><Select value={filter} onChange={(e) => setFilter(e.target.value)} className="pl-9" data-testid="select-product-filter"><option value="all">Todos os produtos</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="low">Estoque baixo</option></Select></div></div>
    <section className="overflow-hidden rounded-xl border border-card-border bg-card shadow-sm">{query.isLoading ? <div className="p-5"><LoadingState rows={6} /></div> : query.isError ? <div className="p-5"><ErrorState onRetry={refresh} /></div> : !products.length ? <div className="p-5"><EmptyState title="Nenhum produto encontrado" detail={search ? "Tente outro termo de busca." : "Cadastre seu primeiro produto para começar."} /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-border bg-muted/50 text-[11px] uppercase tracking-[.1em] text-muted-foreground"><tr><th className="px-5 py-3.5 font-extrabold">Produto</th><th className="px-4 py-3.5 font-extrabold">Preço de venda</th><th className="px-4 py-3.5 font-extrabold">Estoque</th><th className="px-4 py-3.5 font-extrabold">Status</th><th className="px-5 py-3.5 text-right font-extrabold">Ações</th></tr></thead><tbody className="divide-y divide-border">{products.map((p) => <tr key={p.id} data-testid={`row-product-${p.id}`} className="transition hover:bg-muted/30"><td className="px-5 py-4"><div className="font-bold">{p.name}</div><div className="mt-1 font-mono text-[11px] text-muted-foreground">{p.code}</div></td><td className="px-4 py-4 font-mono text-sm">{money.format(p.salePrice)}</td><td className="px-4 py-4"><div className={`font-mono text-sm font-bold ${p.currentStock <= p.minimumStock ? "text-destructive" : ""}`}>{p.currentStock} un.</div><div className="mt-1 text-[11px] text-muted-foreground">mín. {p.minimumStock}</div></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2"><StatusPill status={p.active ? "active" : "inactive"} />{p.active && p.currentStock <= p.minimumStock && <StatusPill status={p.currentStock === 0 ? "OUT" : "LOW"} />}</div></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Link href={`/produtos/${p.id}/editar`} className="rounded-lg p-2 text-muted-foreground transition hover:bg-secondary hover:text-foreground" data-testid={`link-edit-product-${p.id}`} aria-label={`Editar ${p.name}`}><Edit3 size={16} /></Link><Button disabled={toggle.isPending} onClick={() => toggle.mutate({ id: p.id, data: { active: !p.active } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListProductsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); qc.invalidateQueries({ queryKey: getGetLowStockProductsQueryKey() }); } })} className="p-2 text-muted-foreground hover:bg-secondary hover:text-foreground" data-testid={`button-toggle-product-${p.id}`} aria-label={p.active ? `Desativar ${p.name}` : `Ativar ${p.name}`}>{p.active ? <ToggleRight size={19} /> : <ToggleLeft size={19} />}</Button></div></td></tr>)}</tbody></table></div>}</section>
    <div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><CheckCircle2 size={14} className="text-primary" />{products.length} produto{products.length === 1 ? "" : "s"} nesta visão</div>
  </div>;
}