import { ArrowLeft, Check, Package, Save } from "lucide-react";
import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { Link, useLocation, useParams } from "wouter";
import { useCreateProduct, useGetProduct, useUpdateProduct, getGetProductQueryKey, getListProductsQueryKey, getGetDashboardSummaryQueryKey, getGetLowStockProductsQueryKey, getListMovementsQueryKey, getGetRecentMovementsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Button, Field, Input, PageHeader, Saving, Textarea } from "@/components/ui";

type FormState = { code: string; name: string; description: string; salePrice: string; costPrice: string; initialStock: string; minimumStock: string };
const blank: FormState = { code: "", name: "", description: "", salePrice: "", costPrice: "", initialStock: "0", minimumStock: "0" };
export default function ProductForm() {
  const params = useParams<{ id?: string }>(); const editing = Boolean(params.id); const id = Number(params.id); const [location, setLocation] = useLocation(); void location;
  const product = useGetProduct(id, { query: { enabled: editing, queryKey: getGetProductQueryKey(id) } });
  const [form, setForm] = useState<FormState>(blank); const [errors, setErrors] = useState<Record<string, string>>({});
  const create = useCreateProduct(); const update = useUpdateProduct(); const qc = useQueryClient();
  useEffect(() => { if (product.data) setForm({ code: product.data.code, name: product.data.name, description: product.data.description || "", salePrice: String(product.data.salePrice), costPrice: product.data.costPrice == null ? "" : String(product.data.costPrice), initialStock: String(product.data.currentStock), minimumStock: String(product.data.minimumStock) }); }, [product.data]);
  const set = (key: keyof FormState) => (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setForm((v) => ({ ...v, [key]: e.target.value }));
  const submit = (e: FormEvent) => { e.preventDefault(); const salePrice = Number(form.salePrice); const costPrice = form.costPrice ? Number(form.costPrice) : null; const minimumStock = Number(form.minimumStock); const initialStock = Number(form.initialStock); const next: Record<string, string> = {}; if (!form.code.trim()) next.code = "Informe o código."; if (!form.name.trim()) next.name = "Informe o nome."; if (!Number.isFinite(salePrice) || salePrice < 0) next.salePrice = "Informe um preço válido."; if (costPrice !== null && (!Number.isFinite(costPrice) || costPrice < 0)) next.costPrice = "Informe um preço de custo válido."; if (!Number.isFinite(minimumStock) || !Number.isInteger(minimumStock) || minimumStock < 0) next.minimumStock = "Informe um número inteiro válido."; if (!editing && (!Number.isFinite(initialStock) || !Number.isInteger(initialStock) || initialStock < 0)) next.initialStock = "Informe um número inteiro válido."; setErrors(next); if (Object.keys(next).length) return;
    const data = { code: form.code.trim(), name: form.name.trim(), description: form.description.trim() || null, salePrice: Number(form.salePrice), costPrice, minimumStock: Number(form.minimumStock) };
    const common = { onSuccess: () => { qc.invalidateQueries({ queryKey: getListProductsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardSummaryQueryKey() }); qc.invalidateQueries({ queryKey: getGetLowStockProductsQueryKey() }); qc.invalidateQueries({ queryKey: getListMovementsQueryKey() }); qc.invalidateQueries({ queryKey: getGetRecentMovementsQueryKey({ limit: 6 }) }); setLocation("/produtos"); } };
    if (editing) update.mutate({ id, data }, common); else create.mutate({ data: { ...data, initialStock } }, common);
  };
  const pending = create.isPending || update.isPending;
  if (editing && product.isLoading) return <div className="mx-auto max-w-3xl"><PageHeader title="Editar produto" /><div className="grid gap-4"><div className="skeleton h-14 rounded-lg" /><div className="skeleton h-14 rounded-lg" /><div className="skeleton h-40 rounded-lg" /></div></div>;
  return <div className="mx-auto max-w-3xl animate-rise-in"><Link href="/produtos" data-testid="link-back-products" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-muted-foreground transition hover:text-foreground"><ArrowLeft size={16} />Voltar para produtos</Link><PageHeader eyebrow={editing ? "Catálogo / edição" : "Catálogo / novo"} title={editing ? "Editar produto" : "Novo produto"} description={editing ? "Atualize os dados de cadastro sem perder o histórico de estoque." : "Cadastre um item para começar a acompanhar seu saldo."} />
    <form onSubmit={submit} className="overflow-hidden rounded-xl border border-card-border bg-card shadow-sm"><div className="border-b border-border bg-muted/40 px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><Package size={18} /></span><div><div className="text-sm font-extrabold">Dados do produto</div><div className="text-xs text-muted-foreground">Campos marcados com * são obrigatórios.</div></div></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-7"><Field label="Código" required error={errors.code}><Input value={form.code} onChange={set("code")} placeholder="Ex.: BEB-042" maxLength={50} data-testid="input-product-code" /></Field><Field label="Nome do produto" required error={errors.name}><Input value={form.name} onChange={set("name")} placeholder="Ex.: Chá verde 250g" maxLength={150} data-testid="input-product-name" /></Field><Field label="Preço de venda" required hint="Em reais" error={errors.salePrice}><Input type="number" min="0" step="0.01" value={form.salePrice} onChange={set("salePrice")} placeholder="0,00" data-testid="input-product-sale-price" /></Field><Field label="Preço de custo" hint="Opcional" error={errors.costPrice}><Input type="number" min="0" step="0.01" value={form.costPrice} onChange={set("costPrice")} placeholder="0,00" data-testid="input-product-cost-price" /></Field><Field label="Estoque mínimo" required hint="Alerta quando atingir este número" error={errors.minimumStock}><Input type="number" min="0" step="1" value={form.minimumStock} onChange={set("minimumStock")} placeholder="0" data-testid="input-product-minimum-stock" /></Field>{!editing && <Field label="Estoque inicial" hint="Você poderá movimentar depois"><Input type="number" min="0" step="1" value={form.initialStock} onChange={set("initialStock")} placeholder="0" data-testid="input-product-initial-stock" /></Field>}<div className="sm:col-span-2"><Field label="Descrição" hint="Até 500 caracteres"><Textarea value={form.description} onChange={set("description")} maxLength={500} placeholder="Uma breve descrição para facilitar a identificação..." data-testid="input-product-description" /></Field></div></div><div className="flex flex-col-reverse gap-3 border-t border-border bg-muted/20 px-5 py-4 sm:flex-row sm:justify-end sm:px-7"><Link href="/produtos" data-testid="link-cancel-product" className="inline-flex items-center justify-center rounded-lg px-4 py-2.5 text-sm font-bold text-muted-foreground hover:bg-secondary">Cancelar</Link><Button type="submit" disabled={pending} data-testid="button-save-product" className="bg-primary text-primary-foreground shadow-sm">{pending ? <Saving /> : <><Save size={16} />{editing ? "Salvar alterações" : "Cadastrar produto"}</>}</Button></div></form>
  </div>;
}